"""Update Store Logs

Revision ID: 2aca31769f1e
Revises: 8360c16fc47b
Create Date: 2023-08-11 11:27:21.747198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aca31769f1e'
down_revision: Union[str, None] = '8360c16fc47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_store_timezone_store_id', table_name='store_timezone')
    op.drop_index('ix_store_timezone_timezone_str', table_name='store_timezone')
    op.drop_table('store_timezone')
    op.drop_index('ix_store_logs_status', table_name='store_logs')
    op.drop_index('ix_store_logs_store_id', table_name='store_logs')
    op.drop_index('ix_store_logs_timestamp', table_name='store_logs')
    op.drop_table('store_logs')
    op.drop_index('ix_business_hours_day_of_week', table_name='business_hours')
    op.drop_index('ix_business_hours_store_id', table_name='business_hours')
    op.drop_table('business_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_hours',
    sa.Column('store_id', sa.VARCHAR(), nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), nullable=False),
    sa.Column('open_time', sa.DATETIME(), nullable=True),
    sa.Column('close_time', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('store_id', 'day_of_week')
    )
    op.create_index('ix_business_hours_store_id', 'business_hours', ['store_id'], unique=False)
    op.create_index('ix_business_hours_day_of_week', 'business_hours', ['day_of_week'], unique=False)
    op.create_table('store_logs',
    sa.Column('store_id', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.PrimaryKeyConstraint('store_id', 'timestamp')
    )
    op.create_index('ix_store_logs_timestamp', 'store_logs', ['timestamp'], unique=False)
    op.create_index('ix_store_logs_store_id', 'store_logs', ['store_id'], unique=False)
    op.create_index('ix_store_logs_status', 'store_logs', ['status'], unique=False)
    op.create_table('store_timezone',
    sa.Column('store_id', sa.VARCHAR(), nullable=False),
    sa.Column('timezone_str', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index('ix_store_timezone_timezone_str', 'store_timezone', ['timezone_str'], unique=False)
    op.create_index('ix_store_timezone_store_id', 'store_timezone', ['store_id'], unique=False)
    # ### end Alembic commands ###
